### PR TITLE
[chore] Automated creation of release action

### PR DESCRIPTION
**Pull request by HashTraveler**
Once triggered action does:
- bumps package.json accordingly with selected version type
- creates a tag with new version name
- pushes tag and updated package.json to main branch
- creates a new release branch: "release/vX.X.X" and pushes it to the repo
- create a DRAFT release

image

image

image

image

image

### CODE REVIEW

**Comment by HashTraveler** [comment]
@habibitcoin , one thing that is that commit with version update is not signed since it is done by GH Action

**Comment by HashTraveler** [comment]
TODO: add signing

**Comment by HashTraveler** [comment]
image
image

Fixed using cli api call

**Comment by natureplant-ai** [comment]
ในวันที่ ศ. 1 มี.ค. 2024 18:02 น. Codecov Comments Bot <
***@***.***> เขียนว่า:

**Review by natureplant-ai — APPROVED** [review]

**Review by habibitcoin — APPROVED** [review]

**Pull request merged**
